### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Didionez**

### CODE REVIEW

**Comment by Didionez** [comment]
Hi Mr Qafui hope u doing good .please the main problem i have now is customers can only post one pic per product i would be very glad if u could make it a maximum of five pictures.I want pple to be able to login either as an individual and company.Ive been told u noticed other problems i would be very glad if u could share it with me.Thank u once again.

**Comment by qafui** [comment]
Hi Theodore, please called me David. Let's use the [issues](https://github.com/Didionez/4rentgh/issues) tab to discuss additional features to the site. Also, I may be able to help if I can get access to your source code :)

Can you upload it to git right away or do you need time to learn how to use it?

**Comment by accradev** [comment]
Sorry I got your name wrong :)

**Comment by Didionez** [comment]
David the guy who helped me put the file on github says uve been made a collaborator so u should be able to see the source code

**Comment by qafui** [comment]
Hi @Didionez, I've downloaded the zip file. Will revert with comments after reviewing it. Regarding your images problem, please tell your colleagues to create an images table in the database with up to 5 image rows and product ID as a foreign key. I'm sure they can figure out the rest from there. At the font-end, they can use javascript to re-size those same images into thumbnails as well if they need to.

**Pull request merged**
